import { type RouteConfig, index, route } from "@react-router/dev/routes";

export default [
	index("routes/home.tsx"),
	route("login", "routes/login.tsx"),
	route("set-pin", "routes/set-pin.tsx"),
	route("change-pin", "routes/change-pin.tsx"),
	route("forgot-pin", "routes/forgot-pin.tsx"),
	route("reset-pin", "routes/reset-pin.tsx"),
	route("dashboard", "routes/dashboard.tsx"),
	route("scan", "routes/scan.tsx"),
	route("request", "routes/request.tsx"),
	route("request/leave", "routes/request.leave.tsx"),
	route("request/ot", "routes/request.ot.tsx"),
	route("request/time-correction", "routes/request.time-correction.tsx"),
	route("slip", "routes/slip.tsx"),
	route("slip/salary", "routes/slip.salary.tsx"),
	route("slip/ot", "routes/slip.ot.tsx"),
	route("admin", "routes/admin.tsx"),
	route("day-work", "routes/day-work.tsx"),
	route("day-work/view", "routes/day-work.view.tsx"),
	route("api/login", "routes/api.login.ts"),
	route("api/login/set-pin", "routes/api.login.set-pin.ts"),
	route("api/login/change-pin", "routes/api.login.change-pin.ts"),
	route("api/login/daywork", "routes/api.login.daywork.ts"),
	route("api/login/forgot-pin", "routes/api.login.forgot-pin.ts"),
	route("api/login/reset-pin", "routes/api.login.reset-pin.ts"),
	route("api/login/logout", "routes/api.login.logout.ts"),
	route("api/login/admin/issue-temp-pin", "routes/api.login.admin.issue-temp-pin.ts"),
	route("api/login/admin/pin-reset-audit", "routes/api.login.admin.pin-reset-audit.ts"),
	route("api/login/admin/revoke-sessions", "routes/api.login.admin.revoke-sessions.ts"),
	route("api/admin/login", "routes/api.admin.login.ts"),
	route("api/admin/account", "routes/api.admin.account.ts"),
	route("api/admin/account/change-password", "routes/api.admin.account.change-password.ts"),
	route("api/attendance/scan", "routes/api.attendance.scan.ts"),
	route("api/attendance/today", "routes/api.attendance.today.ts"),
	route("api/attendance/verify-location", "routes/api.attendance.verify-location.ts"),
	route("api/attendance/admin/reset-device", "routes/api.attendance.admin.reset-device.ts"),
	route("api/work-locations", "routes/api.work-locations.ts"),
	route("api/leave-request", "routes/api.leave-request.ts"),
	route("api/leave-request/:id", "routes/api.leave-request.$id.ts"),
	route("api/ot-request", "routes/api.ot-request.ts"),
	route("api/ot-request/check-duplicate", "routes/api.ot-request.check-duplicate.ts"),
	route("api/ot-request/:id", "routes/api.ot-request.$id.ts"),
	route("api/time-correction-request", "routes/api.time-correction-request.ts"),
	route("api/request-history", "routes/api.request-history.ts"),
	route("api/salary-slip", "routes/api.salary-slip.ts"),
	route("api/ot-slip", "routes/api.ot-slip.ts"),
	route("api/cloudinary/sign", "routes/api.cloudinary.sign.ts"),
	route("api/map-tiles", "routes/api.map-tiles.ts"),
	route("api/liff-login", "routes/api.liff-login.ts"),
	route("api/line/rich-menu", "routes/api.line.rich-menu.ts"),
	route("api/cron/cleanup-cancelled-leave-files", "routes/api.cron.cleanup-cancelled-leave-files.ts"),
	route("api/verify-pin", "routes/api.verify-pin.ts"),
] satisfies RouteConfig;
